### ISSUE TITLE
Failed to start

### ISSUE THREAD

**Issue by wmdhosting** [webdna/reports#1]
Hey :)

Great plugin .. 

Installed user example.  but generating report  just running .. when i click View button.. 
Nothign in table
------------------------
Craft Pro 4.3.4
DNA Reports  2.3.1

------------------------

![Snag_c8c9f07](https://user-images.githubusercontent.com/76176291/207099925-dd1ed931-33a2-42f3-b42a-76a9105061e2.png)

`yii\base\InvalidArgumentException: Invalid numeric value: * in /home/devkorisnik/vendor/craftcms/cms/src/helpers/Db.php:566
Stack trace:
#0 /home/devkorisnik/vendor/craftcms/cms/src/helpers/Db.php(817): craft\helpers\Db::parseParam('groupId', Array, '=', false, 'integer')
#1 /home/devkorisnik/vendor/craftcms/cms/src/elements/db/UserQuery.php(896): craft\helpers\Db::parseNumericParam('groupId', '*')
#2 /home/devkorisnik/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1294): craft\elements\db\UserQuery->beforePrepare()
#3 /home/devkorisnik/vendor/yiisoft/yii2/db/QueryBuilder.php(227): craft\elements\db\ElementQuery->prepare(Object(craft\db\mysql\QueryBuilder))
#4 /home/devkorisnik/vendor/yiisoft/yii2/db/Query.php(157): yii\db\QueryBuilder->build(Object(craft\elements\db\UserQuery))
#5 /home/devkorisnik/vendor/yiisoft/yii2/db/Query.php(249): yii\db\Query->createCommand(Object(craft\db\Connection))
#6 /home/devkorisnik/vendor/craftcms/cms/src/db/Query.php(248): yii\db\Query->all(NULL)
#7 /home/devkorisnik/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1492): craft\db\Query->all(NULL)
#8 /home/devkorisnik/vendor/twig/twig/src/Extension/CoreExtension.php(1607): craft\elements\db\ElementQuery->all()
#9 /home/devkorisnik/vendor/craftcms/cms/src/helpers/Template.php(110): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\elements\db\UserQuery), 'all', Array, 'method', false, false)
#10 /home/devkorisnik/storage/runtime/compiled_templates/a7/a7d7a05960bcd13c80d6b881a31c439bc194b33a1721aca13e94768f9b826c93.php(57): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\elements\db\UserQuery), 'all', Array, 'method')
#11 /home/devkorisnik/vendor/twig/twig/src/Template.php(394): __TwigTemplate_a363166c8d2462ca6c13aef491acc58586bfec52940d0f392a8da22da9925194->doDisplay(Array, Array)
#12 /home/devkorisnik/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#13 /home/devkorisnik/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array)
#14 /home/devkorisnik/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\Template->render(Array, Array)
#15 /home/devkorisnik/vendor/twig/twig/src/Environment.php(277): Twig\TemplateWrapper->render(Array)
#16 /home/devkorisnik/vendor/craftcms/cms/src/web/View.php(451): Twig\Environment->render('_reports/users/...', Array)
#17 /home/devkorisnik/vendor/webdna/reports/src/services/Reports.php(178): craft\web\View->renderTemplate('_reports/users/...', Array)
#18 /home/devkorisnik/vendor/webdna/reports/src/console/controllers/ReportsController.php(51): webdna\reports\services\Reports->renderTemplate(Object(webdna\reports\models\Report), 'data')
#19 [internal function]: webdna\reports\console\controllers\ReportsController->actionGenerateReport()
#20 /home/devkorisnik/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#21 /home/devkorisnik/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#22 /home/devkorisnik/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('generate-report', Array)
#23 /home/devkorisnik/vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction('generate-report', Array)
#24 /home/devkorisnik/vendor/yiisoft/yii2/base/Controller.php(212): yii\base\Module->runAction('reports/generat...', Array)
#25 /home/devkorisnik/vendor/webdna/reports/src/services/Reports.php(124): yii\base\Controller->run('reports/generat...', Array)
#26 /home/devkorisnik/vendor/webdna/reports/src/controllers/ReportsController.php(160): webdna\reports\services\Reports->runReportById(6)
#27 [internal function]: webdna\reports\controllers\ReportsController->actionRun()
#28 /home/devkorisnik/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#29 /home/devkorisnik/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#30 /home/devkorisnik/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('run', Array)
#31 /home/devkorisnik/vendor/craftcms/cms/src/web/Application.php(301): yii\base\Module->runAction('dnareports/repo...', Array)
#32 /home/devkorisnik/vendor/craftcms/cms/src/web/Application.php(625): craft\web\Application->runAction('dnareports/repo...', Array)
#33 /home/devkorisnik/vendor/craftcms/cms/src/web/Application.php(280): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#34 /home/devkorisnik/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#35 /home/devkorisnik/public_html/index.php(24): yii\base\Application->run()
#36 {main}`

**Comment by samuelbirch** [comment]
it looks like an * is being passed into the groupId attribute.

I would suggest either removing the * from the option values or in the data.twig only set the groupId is the options.userGroupId != *
